include: all_lint_rules.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    included_file_warning: ignore

linter:
  rules:
    public_member_api_docs: false
    prefer_final_parameters: false
    prefer_double_quotes: false
    prefer_expression_function_bodies: false
    always_put_control_body_on_new_line: false
    unnecessary_final: false
    always_specify_types: false
