include: all_lint_rules.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    included_file_warning: ignore

linter:
  rules:
    public_member_api_docs: false
    prefer_final_parameters: false
    prefer_double_quotes: false
    prefer_expression_function_bodies: false
    always_put_control_body_on_new_line: false
    unnecessary_final: false
    always_specify_types: false
    one_member_abstracts: false
    always_use_package_imports: false
    require_trailing_commas: false
    no_leading_underscores_for_local_identifiers: false
    curly_braces_in_flow_control_structures: false
    lines_longer_than_80_chars: false
