name: no_name
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  telephony: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  meta: ^1.10.0

flutter:
  uses-material-design: true
